<?php

return [
    '1' => [
        'id' => 1,
        'name' => 'articles',
        'title' => '文章',
        'class' => 'App\Models\Article',
        'grid' => [
            'title' => '文章管理',
        ],
        'groups' => [
            [
                'name' => 'info',
                'title' => '基本信息',
            ],
            [
                'name' => 'html',
                'title' => '正文',
            ],
        ],
        'fields' => [
            [
                'name' => 'id',         //英文名称
                'title' => 'ID',        //中文名称
                'type' => 'int',        //数据类型
                'length' => 10,         //数据长度
                'system' => true,       //是否是系统字段
                'grid' => [
                    'index' => 0,
                    'show' => true,
                    'align' => 'center',
                    'width' => 30,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 0,       //序号
                    'show' => false,    //是否显示编辑器
                    'type' => '',       //编辑器类型(text,number,select,checkbox,datetime)
                    'rows' => 1,        //编辑器行数
                    'columns' => 0,     //编辑器列数
                    'group' => 'info',      //所属分组
                    'required' => false,//是否必填
                ],
            ],
            [
                'name' => 'site_id',
                'title' => '站点ID',
                'type' => 'int',
                'length' => 10,
                'system' => true,
                'grid' => [
                    'index' => 0,
                    'show' => false,
                    'align' => 'center',
                    'width' => 0,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 0,
                    'show' => false,
                    'type' => '',
                    'rows' => 1,
                    'columns' => 0,
                    'group' => 'info',
                    'required' => false,
                ],
            ],
            [
                'name' => 'category_id',
                'title' => '栏目ID',
                'type' => 'int',
                'length' => 10,
                'system' => true,
                'grid' => [
                    'index' => 0,
                    'show' => false,
                    'align' => 'center',
                    'width' => 0,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 0,
                    'show' => false,
                    'type' => '',
                    'rows' => 1,
                    'columns' => 0,
                    'group' => '',
                    'required' => false,
                ],
            ],
            [
                'name' => 'title',
                'title' => '标题',
                'type' => 'varchar',
                'length' => 255,
                'system' => true,
                'grid' => [
                    'index' => 0,
                    'show' => true,
                    'align' => 'left',
                    'width' => 280,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 1,
                    'show' => true,
                    'type' => 'text',
                    'rows' => 1,
                    'columns' => 11,
                    'group' => 'info',
                    'required' => true,
                ],
            ],
            [
                'name' => 'summary',
                'title' => '摘要',
                'type' => 'text',
                'length' => 0,
                'system' => true,
                'grid' => [
                    'show' => false,
                    'align' => 'left',
                    'width' => 0,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 2,
                    'show' => true,
                    'type' => 'textarea',
                    'rows' => 4,
                    'columns' => 11,
                    'group' => 'info',
                    'required' => false,
                ],
            ],
            [
                'name' => 'image_url',
                'title' => '缩略图',
                'type' => 'text',
                'length' => 0,
                'system' => true,
                'grid' => [
                    'show' => false,
                    'align' => 'left',
                    'width' => 0,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 3,
                    'show' => true,
                    'type' => 'image',
                    'rows' => 1,
                    'columns' => 11,
                    'group' => 'info',
                    'required' => false,
                ],
            ],
            [
                'name' => 'html',
                'title' => '正文',
                'type' => 'text',
                'length' => 0,
                'system' => true,
                'grid' => [
                    'show' => false,
                    'align' => 'left',
                    'width' => 0,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 4,
                    'show' => true,
                    'type' => 'html',
                    'rows' => 40,
                    'columns' => 12,
                    'group' => 'html',
                    'required' => false,
                ],
            ],
            [
                'name' => 'top',
                'title' => '是否置顶',
                'type' => 'int',
                'length' => 10,
                'system' => false,
                'grid' => [
                    'index' => 0,
                    'show' => false,
                    'align' => 'center',
                    'width' => 0,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 0,
                    'show' => false,
                    'type' => '',
                    'rows' => 1,
                    'columns' => 0,
                    'group' => '',
                    'required' => false,
                ],
            ],
            [
                'name' => 'published_at',
                'title' => '发布时间',
                'type' => 'datetime',
                'length' => 0,
                'system' => true,
                'grid' => [
                    'index' => 0,
                    'show' => true,
                    'align' => 'center',
                    'width' => 120,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 5,
                    'show' => false,
                    'type' => '',
                    'rows' => 1,
                    'columns' => 0,
                    'group' => '',
                    'required' => false,
                ],
            ],
            [
                'name' => 'member_id',
                'title' => '会员ID',
                'type' => 'int',
                'length' => 10,
                'system' => true,
                'grid' => [
                    'index' => 0,
                    'title' => '操作员',
                    'show' => false,
                    'align' => 'center',
                    'width' => 0,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 0,
                    'show' => false,
                    'type' => '',
                    'rows' => 1,
                    'columns' => 0,
                    'group' => '',
                    'required' => false,
                ],
            ],
            [
                'name' => 'user_id',
                'title' => '用户ID',
                'type' => 'int',
                'length' => 10,
                'system' => true,
                'grid' => [
                    'index' => 97,
                    'name' => 'user_name',
                    'title' => '操作员',
                    'show' => true,
                    'align' => 'center',
                    'width' => 0,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 0,
                    'show' => false,
                    'type' => '',
                    'rows' => 1,
                    'columns' => 0,
                    'group' => '',
                    'required' => false,
                ],
            ],
            [
                'name' => 'sort',
                'title' => '排序',
                'type' => 'int',
                'length' => 10,
                'system' => true,
                'grid' => [
                    'index' => 0,
                    'show' => false,
                    'align' => 'center',
                    'width' => 0,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 0,
                    'show' => false,
                    'type' => '',
                    'rows' => 1,
                    'columns' => 0,
                    'group' => 'info',
                    'required' => false,
                ],
            ],
            [
                'name' => 'state',
                'title' => '状态',
                'type' => 'int',
                'length' => 10,
                'system' => true,
                'grid' => [
                    'index' => 96,
                    'show' => true,
                    'align' => 'center',
                    'width' => 0,
                    'formatter' => 'stateFormatter',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 0,
                    'show' => false,
                    'type' => '',
                    'rows' => 1,
                    'columns' => 0,
                    'group' => '',
                    'required' => false,
                ],
            ],
            [
                'name' => 'created_at',
                'title' => '创建时间',
                'type' => 'datetime',
                'length' => 0,
                'system' => true,
                'grid' => [
                    'index' => 98,
                    'show' => false,
                    'title' => '录入时间',
                    'align' => 'center',
                    'width' => 120,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 0,
                    'show' => false,
                    'type' => '',
                    'rows' => 1,
                    'columns' => 0,
                    'group' => '',
                    'required' => false,
                ],
            ],
            [
                'name' => 'updated_at',
                'title' => '修改时间',
                'type' => 'datetime',
                'length' => 0,
                'system' => true,
                'grid' => [
                    'index' => 99,
                    'show' => false,
                    'title' => '修改时间',
                    'align' => 'center',
                    'width' => 120,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 0,
                    'show' => false,
                    'type' => '',
                    'rows' => 1,
                    'columns' => 0,
                    'group' => '',
                    'required' => false,
                ],
            ],
            [
                'name' => 'deleted_at',
                'title' => '删除时间',
                'type' => 'datetime',
                'length' => 0,
                'system' => true,
                'grid' => [
                    'index' => 0,
                    'show' => false,
                    'align' => 'left',
                    'width' => 0,
                    'formatter' => '',
                    'editable' => false,
                ],
                'editor' => [
                    'index' => 0,
                    'show' => false,
                    'type' => '',
                    'rows' => 1,
                    'columns' => 0,
                    'group' => '',
                    'required' => false,
                ],
            ],
        ],
    ],
];