<?php

return [
    '1' => [
        'jpush' => [
            'app_key' => '5891f2f9549ba634488f9a74',
            'master_secret' => '9376fda52b4dd8525800cb16',
        ],
        'watermark' => [
            'enabled' => true,
            'path' => 'images/watermark.png'
        ],
        'sms' => [
            'template' => [
                '0' => '',
                '1' => '',
                '2' => '',
                '3' => '',
                '4' => '',
            ],
        ],
    ],

    'cdn' => [
        'image_url' => '',
        'video_url' => '',
        'static_url' => '',
    ],

    'upload' => [
        'url_prefix' => '',
        'avatar_path' => '/uploads/avatars',
        'video_path' => '/uploads/videos',
        'audio_path' => '/uploads/audios',
        'image_path' => '/uploads/images',
        'other_path' => '/uploads/others',
    ],

    'model' => [
        '1' => [
            'id' => 1,
            'name' => 'news',
            'title' => '新闻',
            'tabs' => [
                [
                    'name' => 'info',
                    'title' => '基本信息',
                ],
                [
                    'name' => 'content',
                    'title' => '正文',
                ]
            ],
            'fields' => [
                [
                    'name' => 'id',
                    'title' => 'ID',
                    'type' => 'int',
                    'length' => 10,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'center',
                        'width' => 30,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 0,
                        'show' => false,
                        'type' => '',
                        'rows' => 1,
                        'columns' => 0,
                        'tab' => '',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'category_id',
                    'title' => '栏目ID',
                    'type' => 'int',
                    'length' => 10,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 0,
                        'show' => false,
                        'type' => '',
                        'rows' => 1,
                        'columns' => 0,
                        'tab' => '',
                        'required' => true,
                    ],
                ],
                [
                    'name' => 'type',
                    'title' => '类型',
                    'type' => 'tinyint',
                    'length' => 10,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 5,
                        'show' => true,
                        'type' => 'select',
                        'options' => [
                            1 => '小图',
                            2 => '大图',
                            3 => '多图',
                        ],
                        'rows' => 1,
                        'columns' => 2,
                        'tab' => 'info',
                        'required' => true,
                    ],
                ],
                [
                    'name' => 'title',
                    'title' => '标题',
                    'type' => 'varchar',
                    'length' => 255,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'left',
                        'width' => 280,
                        'formatter' => 'titleFormatter',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 1,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 11,
                        'tab' => 'info',
                        'required' => true,
                    ],
                ],
                [
                    'name' => 'subtitle',
                    'title' => '副标题',
                    'type' => 'varchar',
                    'length' => 255,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 2,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 5,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'author',
                    'title' => '作者',
                    'type' => 'varchar',
                    'length' => 20,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 3,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 2,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'source',
                    'title' => '来源',
                    'type' => 'varchar',
                    'length' => 20,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 4,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 2,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'tags',
                    'title' => '标签',
                    'type' => 'varchar',
                    'length' => 255,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'center',
                        'width' => 60,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 5,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 2,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'keywords',
                    'title' => '关键字',
                    'type' => 'varchar',
                    'length' => 255,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 6,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 5,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'summary',
                    'title' => '摘要',
                    'type' => 'text',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 8,
                        'show' => true,
                        'type' => 'textarea',
                        'rows' => 4,
                        'columns' => 11,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'image_url',
                    'title' => '图片地址',
                    'type' => 'text',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 9,
                        'show' => true,
                        'type' => 'image',
                        'rows' => 1,
                        'columns' => 11,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'images',
                    'title' => '图集',
                    'type' => 'text',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 10,
                        'show' => true,
                        'type' => 'images',
                        'rows' => 1,
                        'columns' => 11,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'video_url',
                    'title' => '视频地址',
                    'type' => 'text',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 11,
                        'show' => true,
                        'type' => 'video',
                        'rows' => 1,
                        'columns' => 11,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'audio_url',
                    'title' => '音频地址',
                    'type' => 'text',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 12,
                        'show' => true,
                        'type' => 'audio',
                        'rows' => 1,
                        'columns' => 11,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'content',
                    'title' => '正文',
                    'type' => 'text',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 13,
                        'show' => true,
                        'type' => 'html',
                        'rows' => 40,
                        'columns' => 12,
                        'tab' => 'content',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'clicks',
                    'title' => '点击量',
                    'type' => 'int',
                    'length' => 10,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'center',
                        'width' => 45,
                        'formatter' => '',
                        'editable' => true,
                    ],
                    'editor' => [
                        'index' => 0,
                        'show' => false,
                        'type' => '',
                        'rows' => 1,
                        'columns' => 0,
                        'tab' => '',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'state',
                    'title' => '状态',
                    'type' => 'tinyint',
                    'length' => 1,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'center',
                        'width' => 45,
                        'formatter' => 'stateFormatter',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 0,
                        'show' => false,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 0,
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'published_at',
                    'title' => '发布时间',
                    'type' => 'datetime',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'center',
                        'width' => 110,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 7,
                        'show' => true,
                        'type' => 'datetime',
                        'rows' => 1,
                        'columns' => 5,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
            ],
        ],
        '2' => [
            'id' => 2,
            'name' => 'video',
            'title' => '视频',
            'tabs' => [
                [
                    'name' => 'info',
                    'title' => '基本信息',
                ],
                [
                    'name' => 'content',
                    'title' => '正文',
                ]
            ],
            'fields' => [
                [
                    'name' => 'id',
                    'title' => 'ID',
                    'type' => 'int',
                    'length' => 10,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'center',
                        'width' => 30,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 0,
                        'show' => false,
                        'type' => '',
                        'rows' => 1,
                        'columns' => 0,
                        'tab' => '',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'category_id',
                    'title' => '栏目ID',
                    'type' => 'int',
                    'length' => 10,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 0,
                        'show' => false,
                        'type' => '',
                        'rows' => 1,
                        'columns' => 0,
                        'tab' => '',
                        'required' => true,
                    ],
                ],
                [
                    'name' => 'type',
                    'title' => '类型',
                    'type' => 'tinyint',
                    'length' => 10,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 5,
                        'show' => true,
                        'type' => 'select',
                        'options' => [
                            1 => '小图',
                            2 => '大图',
                            3 => '多图',
                        ],
                        'rows' => 1,
                        'columns' => 2,
                        'tab' => 'info',
                        'required' => true,
                    ],
                ],
                [
                    'name' => 'title',
                    'title' => '标题',
                    'type' => 'varchar',
                    'length' => 255,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'left',
                        'width' => 280,
                        'formatter' => 'titleFormatter',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 1,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 11,
                        'tab' => 'info',
                        'required' => true,
                    ],
                ],
                [
                    'name' => 'subtitle',
                    'title' => '副标题',
                    'type' => 'varchar',
                    'length' => 255,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 2,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 5,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'author',
                    'title' => '作者',
                    'type' => 'varchar',
                    'length' => 20,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 3,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 2,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'source',
                    'title' => '来源',
                    'type' => 'varchar',
                    'length' => 20,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 4,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 2,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'tags',
                    'title' => '标签',
                    'type' => 'varchar',
                    'length' => 255,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'center',
                        'width' => 60,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 5,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 2,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'keywords',
                    'title' => '关键字',
                    'type' => 'varchar',
                    'length' => 255,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 6,
                        'show' => true,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 5,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'summary',
                    'title' => '摘要',
                    'type' => 'text',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 8,
                        'show' => true,
                        'type' => 'textarea',
                        'rows' => 4,
                        'columns' => 11,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'image_url',
                    'title' => '图片地址',
                    'type' => 'text',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 9,
                        'show' => true,
                        'type' => 'image',
                        'rows' => 1,
                        'columns' => 11,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'video_url',
                    'title' => '视频地址',
                    'type' => 'text',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 11,
                        'show' => true,
                        'type' => 'video',
                        'rows' => 1,
                        'columns' => 11,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'content',
                    'title' => '正文',
                    'type' => 'text',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => false,
                        'align' => 'left',
                        'width' => 0,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 13,
                        'show' => true,
                        'type' => 'html',
                        'rows' => 40,
                        'columns' => 12,
                        'tab' => 'content',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'clicks',
                    'title' => '点击量',
                    'type' => 'int',
                    'length' => 10,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'center',
                        'width' => 45,
                        'formatter' => '',
                        'editable' => true,
                    ],
                    'editor' => [
                        'index' => 0,
                        'show' => false,
                        'type' => '',
                        'rows' => 1,
                        'columns' => 0,
                        'tab' => '',
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'state',
                    'title' => '状态',
                    'type' => 'tinyint',
                    'length' => 1,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'center',
                        'width' => 45,
                        'formatter' => 'stateFormatter',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 0,
                        'show' => false,
                        'type' => 'text',
                        'rows' => 1,
                        'columns' => 0,
                        'required' => false,
                    ],
                ],
                [
                    'name' => 'published_at',
                    'title' => '发布时间',
                    'type' => 'datetime',
                    'length' => 0,
                    'system' => true,
                    'table' => [
                        'show' => true,
                        'align' => 'center',
                        'width' => 110,
                        'formatter' => '',
                        'editable' => false,
                    ],
                    'editor' => [
                        'index' => 7,
                        'show' => true,
                        'type' => 'datetime',
                        'rows' => 1,
                        'columns' => 5,
                        'tab' => 'info',
                        'required' => false,
                    ],
                ],
            ],
        ],
    ]
];